kind: pipeline
type: docker
name: test

steps:
  - name: Test Node
    image: node:25
    commands:
      - curl https://qlty.sh | sh
      - curl -fsSL https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
      - export PNPM_HOME="$HOME/.local/share/pnpm" && export PATH="$PNPM_HOME:$PATH"
      - pnpm install
      - pnpm test
      - ~/.qlty/bin/qlty coverage publish coverage/lcov.info --override-commit-sha "$DRONE_COMMIT_SHA" --override-branch "$DRONE_BRANCH" --override-build-id "$DRONE_BUILD_NUMBER"
    environment:
      QLTY_COVERAGE_TOKEN: qltcp_GJthltuZvY2mx08Z
