kind: pipeline
type: docker
name: test

steps:
  - name: Test Node
    image: node:25
    commands:
      - curl https://qlty.sh | sh
      - npm ci
      - npm test
      - ~/.qlty/bin/qlty coverage publish coverage/lcov.info --override-commit-sha "$DRONE_COMMIT_SHA" --override-branch "$DRONE_BRANCH" --override-build-id "$DRONE_BUILD_NUMBER"
    environment:
      QLTY_COVERAGE_TOKEN: qltcp_GJthltuZvY2mx08Z

  - name: Publish Node
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    image: node:24
    commands:
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" > ~/.npmrc
      - npm whoami
      - npm publish
    when:
      event:
        - tag
